import assert from 'node:assert/strict';import test from 'node:test';import{harness,Three}from'./helpers/defense-harness.mjs';
test('shotgun hits several close targets while sniper trades energy for a precise shot',async()=>{const g=await harness();try{g.renderer.xr.isPresenting=false;g.d.cleared=4;g.d.start();g.d.queued=0;g.cycleMode();assert.equal(g.state().mode,1);
 for(let i=0;i<3;i++){g.d.spawn();g.d.x[i]=i===0?-.5:i===1?.5:0;g.d.z[i]=i===2?-12:1;g.d.y[i]=0;g.d.hp[i]=g.d.max[i]=5;}
 g.tick();g.state().weapon.press(true);g.updateBeam(.016,1);assert.ok(g.d.hp[0]<5&&g.d.hp[1]<5);assert.equal(g.d.hp[2],5);assert.equal(g.state().weapon.energy,10.5);g.updateBeam(.016,1);assert.equal(g.state().weapon.energy,10.5);
 g.cycleMode();g.d.flags[0]=g.d.flags[1]=0;g.d.z[2]=-10;g.state().weapon.press(false);g.state().weapon.press(true);g.tick();g.updateBeam(.016,1);assert.ok(g.d.hp[2]<3);assert.ok(Math.abs(g.state().weapon.energy-8.1)<1e-9);assert.equal(g.state().mode,2);
 }finally{g.restore();}});
test('build phase does not consume weapon energy; sparse renderer and resets remain bounded',async()=>{const g=await harness();try{g.state().weapon.press(true);g.updateBeam(1,1);assert.equal(g.state().weapon.energy,12);g.d.wave=1;g.d.queued=1;for(let i=0;i<g.d.flags.length;i++)g.d.spawn();g.d.flags.fill(0);g.d.flags[4]=1;g.d.flags[g.d.flags.length-1]=1|16|32;g.species.sync(1);const meshes=g.scene.children.filter(o=>o.isInstancedMesh);assert.equal(meshes[0].count,2);const buffers=meshes.map(m=>m.instanceMatrix.array);for(let i=0;i<100;i++){g.resetRun();g.species.sync(1);}assert.equal(meshes[0].count,0);buffers.forEach((b,i)=>assert.equal(meshes[i].instanceMatrix.array,b));}finally{g.restore();}});

test('canonical tower families grow on upgrade and reuse their models across resets',async()=>{const g=await harness();try{const roots=[...g.towerModels];g.d.credits=1000;g.d.cleared=2;g.d.build(0);g.d.build(1,1);g.updateTowers(0);assert.equal(roots[0].children[0].visible,true);assert.equal(roots[1].children[1].visible,true);const before=roots[0].scale.x;g.d.build(0);g.updateTowers(1);assert.ok(roots[0].scale.x>before);assert.equal(roots[1].children[1].children[1].rotation.y,.5);for(let i=0;i<100;i++){g.resetRun();g.updateTowers(i);assert.ok(roots.every(m=>!m.visible));assert.deepEqual(g.towerModels,roots);}}finally{g.restore()}});
