import {towerSubsetPlugin} from './tower-subset.mjs';
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {build} from 'esbuild';
import {packGame} from './pack-game.mjs';
const iwer=await readFile('node_modules/iwer/build/iwer.js','utf8');
// Test-only observability, bundled separately; never added to the competition archive.
let source=await readFile('competition/game.js','utf8');
source=source.replace(/\n}\s*$/,`\nglobalThis.inspectGame={towerMenu,cards,pouch,discard,weapon:()=>({...weapon}),d,gun,grips,controllers,cartridge,handle,emitter,rig,renderer,scene,beamMesh,hands,board,reloadHint,state:()=>({active,score:d.score,wave:d.wave,mode,firing,holding,gunHand,input:inputSource?.handedness}),x,y,z,flags};\n}`);
let bundled=(await build({plugins:[towerSubsetPlugin],stdin:{contents:source,resolveDir:process.cwd()+'/competition',loader:'js'},bundle:true,write:false,format:'esm'})).outputFiles[0].text;
bundled=(await packGame(bundled)).game;
let html=(await readFile('competition/index.html','utf8')).replace('<script type=module src=game.js></script>',`<script type=module>${bundled}</script>`);
const b=await chromium.launch({channel:'chrome'});try{const p=await b.newPage({viewport:{width:1200,height:800}});const errors=[],requests=[];p.on('requestfinished',r=>requests.push(r.url()));
p.on('pageerror',e=>errors.push(e.stack));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await p.addInitScript({content:iwer+`;globalThis.xrDevice=new IWER.XRDevice(IWER.metaQuest3,{stereoEnabled:true});xrDevice.installRuntime({forceInstall:true});`});
await p.route('**/xr-test',r=>r.fulfill({body:html,contentType:'text/html'}));
await p.goto('http://127.0.0.1:4173/xr-test');await p.locator('#v').click();await p.waitForTimeout(1000);await p.waitForFunction(()=>inspectGame.hands.every(h=>h?.el.object3D.children.length));
const handModels=await p.evaluate(()=>inspectGame.hands.map(h=>{let skinned=0;h.el.object3D.traverse(o=>skinned+=!!o.isSkinnedMesh);return{hand:h.data.hand,skinned,clips:h.clips.map(c=>c.name),gesture:h.gesture};}));assert.deepEqual(handModels.map(h=>h.hand),['left','right']);assert.ok(handModels.every(h=>h.skinned>0&&h.clips.includes('Fist')));

const initialHandIds=await p.evaluate(()=>inspectGame.hands.map(h=>h.el.object3D.uuid));
const records=[];
async function record(label){records.push({label,...await p.evaluate(()=>({state:inspectGame.state(),weapon:inspectGame.weapon(),hint:inspectGame.reloadHint(),handPoses:inspectGame.hands.map(h=>({hand:h.data.hand,pose:h.gesture||'Open',visible:h.el.object3D.visible})),render:inspectGame.renderer.info.render,memory:inspectGame.renderer.info.memory}))});}
async function button(hand,name,value){await p.evaluate(([h,n,v])=>xrDevice.controllers[h].updateButtonValue(n,v),[hand,name,value]);await p.waitForTimeout(65);}
async function placeHand(local,side='left'){for(let j=0;j<2;j++){await p.evaluate(([local,side])=>{const g=inspectGame,T=AFRAME.THREE;g.gun.updateWorldMatrix(true,false);const wanted=g.gun.localToWorld(new T.Vector3(...local));const c=g.controllers.find(c=>c.userData.source?.handedness===side);const actual=g.grips[g.controllers.indexOf(c)].localToWorld(new T.Vector3(0,-.01,.02));xrDevice.controllers[side].position.x+=wanted.x-actual.x;xrDevice.controllers[side].position.y+=wanted.y-actual.y;xrDevice.controllers[side].position.z+=wanted.z-actual.z;},[local,side]);await p.waitForTimeout(65);}}
async function aimAt(target){for(let i=0;i<3;i++){await p.evaluate(target=>{const g=inspectGame,T=AFRAME.THREE,c=xrDevice.controllers.right;g.scene.updateMatrixWorld(true);const q=g.gun.getWorldQuaternion(new T.Quaternion()),origin=g.emitter.getWorldPosition(new T.Vector3()),dir=new T.Vector3(...target).sub(origin).normalize(),wanted=new T.Quaternion().setFromUnitVectors(new T.Vector3(0,0,-1),dir);wanted.multiply(q.invert());const current=new T.Quaternion(c.quaternion.x,c.quaternion.y,c.quaternion.z,c.quaternion.w).premultiply(wanted);c.quaternion.set(current.x,current.y,current.z,current.w);},target);await p.waitForTimeout(60);}}
// Actual XR gamepad axes, including a held turn that must not repeat.
const initialPose=await p.evaluate(()=>({z:inspectGame.rig.position.z,yaw:inspectGame.rig.rotation.y}));
await p.evaluate(()=>xrDevice.controllers.right.updateAxes('thumbstick',1,0));await p.waitForTimeout(200);
const snapped=await p.evaluate(()=>inspectGame.rig.rotation.y);assert.ok(Math.abs(snapped-initialPose.yaw+Math.PI/6)<.001);
await p.waitForTimeout(350);assert.equal(await p.evaluate(()=>inspectGame.rig.rotation.y),snapped);
await p.evaluate(()=>xrDevice.controllers.right.updateAxes('thumbstick',0,0));await p.waitForTimeout(80);
await p.evaluate(()=>xrDevice.controllers.right.updateAxes('thumbstick',-1,0));await p.waitForTimeout(100);await p.evaluate(()=>xrDevice.controllers.right.updateAxes('thumbstick',0,0));await p.waitForTimeout(80);assert.ok(Math.abs(await p.evaluate(()=>inspectGame.rig.rotation.y))<.001);
await p.evaluate(()=>xrDevice.controllers.left.updateAxes('thumbstick',0,-1));await p.waitForTimeout(250);await p.evaluate(()=>xrDevice.controllers.left.updateAxes('thumbstick',0,0));await p.waitForTimeout(80);assert.ok(await p.evaluate(()=>inspectGame.rig.position.z)<initialPose.z-.3);await record('left movement and latched right snap turn');
assert.equal(await p.evaluate(()=>inspectGame.cards.filter(c=>c.card.visible&&c.model.children.length).length),5);await aimAt([3.2,1.3,2]);await button('right','trigger',1);await button('right','trigger',0);assert.equal(await p.evaluate(()=>inspectGame.state().mode),0);assert.match(await p.locator('#t').innerText(),/LOCKED/);await record('all five models visible; locked card rejects equip');
await p.evaluate(()=>xrDevice.controllers.right.position.set(.15,1.4,-.45));await aimAt([0,3.14,0]);await button('right','squeeze',1);await button('right','squeeze',0);assert.equal(await p.evaluate(()=>inspectGame.d.credits),70,'holding the gun must not buy a tower');await button('right','trigger',1);await button('right','trigger',0);await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>inspectGame.d.towers[0]),1,'physical board trigger builds first tower');await record('first tower built');await aimAt([-4,1.2,-3]);await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>inspectGame.towerMenu.visible),true);await aimAt(await p.evaluate(()=>inspectGame.towerMenu.localToWorld(new AFRAME.THREE.Vector3(0,.13,0)).toArray()));await button('right','trigger',1);await button('right','trigger',0);assert.equal(await p.evaluate(()=>inspectGame.d.towers[0]),1);assert.equal(await p.evaluate(()=>inspectGame.d.credits),35);await record('nearby tower menu rejects unaffordable upgrade');await aimAt(await p.evaluate(()=>inspectGame.towerMenu.localToWorld(new AFRAME.THREE.Vector3(0,-.32,0)).toArray()));await button('right','trigger',1);await button('right','trigger',0);await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>inspectGame.d.wave),1,'physical board trigger starts a wave');
await aimAt(await p.evaluate(()=>[inspectGame.x[0],inspectGame.y[0]+1.25,inspectGame.z[0]]));
await button('right','trigger',1);
// Follow the moving target until the simulation reports a recovery; fixed wall time
// under-runs on throttled XR emulation. This still uses real poses and trigger input.
for(let i=0;i<40&&!await p.evaluate(()=>inspectGame.state().score>0);i++){await aimAt(await p.evaluate(()=>[inspectGame.x[0],inspectGame.y[0]+1.25,inspectGame.z[0]]));await button('right','trigger',0);await button('right','trigger',1);}
await button('right','trigger',0);await record('first recovery with trigger');
await placeHand([0,-.10,-.07]);await button('left','squeeze',1);
for(let i=0;i<8;i++){await p.evaluate(()=>{xrDevice.controllers.left.position.x+=.045;xrDevice.controllers.left.position.y+=.012;});await p.waitForTimeout(20);}
const thrownFrom=await p.evaluate(()=>inspectGame.cartridge.getWorldPosition(new AFRAME.THREE.Vector3()).toArray());await button('left','squeeze',0);await p.waitForTimeout(80);
const thrownTo=await p.evaluate(()=>inspectGame.cartridge.getWorldPosition(new AFRAME.THREE.Vector3()).toArray());
assert.ok(thrownTo[0]>thrownFrom[0]+.04,'released magazine carries actual controller momentum');assert.equal(await p.evaluate(()=>inspectGame.cartridge.parent===inspectGame.scene),true);await record('magazine thrown with controller motion');await p.screenshot({path:'evidence/xr-throw.png'});
const removedEnergy=await p.evaluate(()=>inspectGame.weapon().energy);await button('right','a-button',1);await button('right','a-button',0);await button('left','trigger',1);await button('left','trigger',0);await p.keyboard.press('r');await p.waitForTimeout(300);assert.equal(await p.evaluate(()=>inspectGame.weapon().assist),0);assert.equal(await p.evaluate(()=>inspectGame.weapon().seated),false);assert.equal(await p.evaluate(()=>inspectGame.weapon().energy),removedEnergy);assert.equal(await p.locator('#reload').isVisible(),false);await record('VR automatic reload inputs blocked');await placeHand(await p.evaluate(()=>inspectGame.gun.worldToLocal(inspectGame.pouch.position.clone()).toArray()));await button('left','squeeze',1);await placeHand([0,-.10,-.07]);await button('left','squeeze',0);await p.waitForFunction(()=>inspectGame.weapon().primed);
await placeHand([0,-.10,-.07]);await button('left','squeeze',1);await placeHand([0,-.32,-.07]);await record('cartridge removed');await p.screenshot({path:'evidence/xr-cartridge.png'});
await button('left','squeeze',0);await placeHand(await p.evaluate(()=>inspectGame.gun.worldToLocal(inspectGame.pouch.position.clone()).toArray()));await button('left','squeeze',1);await record('left hip fresh magazine');assert.equal(await p.evaluate(()=>inspectGame.weapon().energy),12);assert.equal(await p.evaluate(()=>inspectGame.state().holding),1);assert.equal(await p.evaluate(()=>inspectGame.discard.visible),true);
await p.evaluate(()=>xrDevice.quaternion.set(-Math.sin(.45),0,0,Math.cos(.45)));await p.waitForTimeout(150);await p.screenshot({path:'evidence/xr-hip-pouch.png'});await p.evaluate(()=>xrDevice.quaternion.set(0,0,0,1));await p.waitForTimeout(100);
await placeHand([0,-.10,-.07]);await button('left','squeeze',0);await p.waitForFunction(()=>inspectGame.weapon().primed);await record('automatic chamber ready');await p.screenshot({path:'evidence/xr-auto-chamber.png'});
await placeHand([0,-.10,-.07]);await button('left','squeeze',1);await placeHand([0,-.32,-.07]);await button('left','squeeze',0);await p.evaluate(()=>xrDevice.controllers.left.connected=false);await p.waitForTimeout(120);await button('right','a-button',1);await button('right','a-button',0);assert.equal(await p.evaluate(()=>inspectGame.weapon().assist),0);assert.equal(await p.evaluate(()=>inspectGame.weapon().primed),false);await record('one controller requires hands');
await p.evaluate(()=>inspectGame.renderer.xr.getSession().end());await p.waitForTimeout(200);await record('exit');await p.keyboard.press('r');await p.waitForFunction(()=>inspectGame.weapon().primed&&!inspectGame.weapon().assist);await record('desktop assisted recovery');await p.locator('#v').click();await p.waitForTimeout(400);await record('reentry');await p.evaluate(()=>inspectGame.d.cleared=4);await aimAt([3.2,2.2,2]);await button('right','trigger',1);await button('right','trigger',0);await record('shotgun unlocked');await aimAt([3.2,1.3,2]);await button('right','trigger',1);await button('right','trigger',0);await record('sniper unlocked');
await p.evaluate(()=>xrDevice.controllers.left.connected=true);await p.waitForTimeout(150);await placeHand([0,-.055,.035]);await button('left','squeeze',1);await button('left','squeeze',0);await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>inspectGame.state().input),'left',JSON.stringify(await p.evaluate(()=>({state:inspectGame.state(),weapon:inspectGame.weapon(),health:inspectGame.d.health})))) ;await record('physical gun handover');
await placeHand([0,-.10,-.07],'right');await button('right','squeeze',1);await placeHand([0,-.32,-.07],'right');await record('left gun cartridge removed');await button('right','squeeze',0);await placeHand(await p.evaluate(()=>inspectGame.gun.worldToLocal(inspectGame.pouch.position.clone()).toArray()),'right');await button('right','squeeze',1);await record('right hip fresh magazine');assert.equal(await p.evaluate(()=>inspectGame.weapon().energy),12);assert.equal(await p.evaluate(()=>inspectGame.state().holding),1);await placeHand([0,-.10,-.07],'right');await button('right','squeeze',0);
await p.waitForFunction(()=>inspectGame.weapon().primed);await record('left gun ready');
assert.deepEqual(await p.evaluate(()=>inspectGame.hands.map(h=>h.el.object3D.uuid)),initialHandIds);
assert.equal(requests.filter(u=>u.includes('/controllers/hands/')).length,2,'reentry reuses the two default hand models');
await p.waitForFunction(()=>!document.querySelector('#m').textContent.includes('RELEASE GRIP'));await p.screenshot({path:'evidence/xr-final.png'});
await writeFile('evidence/xr-browser.json',JSON.stringify({browser:await b.version(),iwer:'2.3.0',mode:'packed instrumented production source; actual IWER poses and button events; not headset hardware or the unmodified competition artifact',errors,requests,handModels,throwMotion:{thrownFrom,thrownTo},records},null,2));
assert.equal(errors.length,0);const at=label=>records.find(r=>r.label===label);assert.equal(at('first recovery with trigger').state.score>0,true);assert.equal(at('cartridge removed').weapon.seated,false);assert.equal(at('automatic chamber ready').weapon.primed,true);assert.equal(at('one controller requires hands').weapon.primed,false);assert.equal(at('reentry').state.firing,false);assert.equal(at('shotgun unlocked').state.mode,1);assert.equal(at('sniper unlocked').state.mode,2);assert.equal(at('left gun cartridge removed').weapon.seated,false);assert.equal(at('left gun ready').weapon.primed,true);console.log('IWER defense, hands and reload checks passed');}finally{await b.close();}
