import assert from 'node:assert/strict';import{readFile,writeFile,mkdir}from'node:fs/promises';import{chromium}from'playwright';
const source=await readFile('competition/game.js','utf8'),audio=source.slice(source.indexOf('let audioContext'),source.indexOf('const cover='));
const shot=source.slice(source.indexOf('tone([520'),source.indexOf('twinkle(.5)',source.indexOf('tone([520'))),click=source.match(/function clickMechanism\(f\)\{([^;]+;)/)[1],tower=source.match(/tone\(d\.towerType\[i\][^;]+;/)[0],wave=source.match(/tone\(\(d\.cleared===6[^;]+;/)[0];
const cases={pistol:'const mode=0;'+shot,shotgun:'const mode=1;'+shot,sniper:'const mode=2;'+shot,remove:'const f=1100;'+click,insert:'const f=550;'+click,ready:'const f=880;'+click,prism:'const d={towerType:[0]},i=0;'+tower,slow:'const d={towerType:[1]},i=0;'+tower,recovery:'chord();',build:'chord(440);',start:'chord(330);',wave:'const d={cleared:2};for(let i=0;i<6;i++){'+wave+'}',victory:'const d={cleared:6};for(let i=0;i<6;i++){'+wave+'}',damage:source.match(/tone\(160,[^;]+;/)[0],defeat:source.match(/tone\(220,[^;]+;/)[0]};
cases.mixed=Object.values(cases).map(code=>'{'+code+'}').join('');
await mkdir('evidence/audio',{recursive:true});const b=await chromium.launch({channel:'chrome'}),report={browser:b.version(),method:'actual production Web Audio synthesizer and cue expressions, OfflineAudioContext 48kHz mono; instrumentation and WAVs not shipped',cases:[]};
try{const p=await b.newPage();await p.goto('about:blank');await p.evaluate(code=>{Function(code+`globalThis.renderSound=async expression=>{audioContext=new OfflineAudioContext(1,48000,48000);eval(expression);const result=await audioContext.startRendering();return Array.from(result.getChannelData(0));}`)();},audio);
 for(const[name,expression]of Object.entries(cases)){const values=await p.evaluate(expression=>renderSound(expression),expression);let peak=0,power=0,last=0;for(let i=0;i<values.length;i++){const v=values[i];assert.ok(Number.isFinite(v));peak=Math.max(peak,Math.abs(v));power+=v*v;if(Math.abs(v)>.001)last=i;}assert.ok(peak>.002&&peak<.95,name+' audible and unclipped');const wav=Buffer.alloc(44+values.length*2);wav.write('RIFF',0);wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(48000,24);wav.writeUInt32LE(96000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(values.length*2,40);values.forEach((v,i)=>wav.writeInt16LE(Math.round(v*32767),44+i*2));await writeFile(`evidence/audio/${name}.wav`,wav);report.cases.push({name,peak,rms:Math.sqrt(power/values.length),audibleDuration:last/48000});}
 await writeFile('evidence/audio/render.json',JSON.stringify(report,null,2));console.log(report);
}finally{await b.close();}
